//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHocThem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLaiThuHocPhi
    {
        public int Ma { get; set; }
        public Nullable<int> TongSoBuoi { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<int> MaHocSinh { get; set; }
        public Nullable<int> MaLopHoc { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
