//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHocThem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLaiTraLuong
    {
        public int Ma { get; set; }
        public Nullable<int> SoTienMotBuoi { get; set; }
        public Nullable<int> TongSoBuoi { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayTraLuong { get; set; }
        public Nullable<System.DateTime> LuongTheoThang { get; set; }
        public Nullable<int> MaGiaoVien { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
    }
}
