//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHocThem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public int MaBuoiHoc { get; set; }
        public int MaHocSinh { get; set; }
        public Nullable<bool> DaDiemDanh { get; set; }
    
        public virtual BuoiHoc BuoiHoc { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
