//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHocThem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.BienLaiThuHocPhis = new HashSet<BienLaiThuHocPhi>();
            this.BuoiHocs = new HashSet<BuoiHoc>();
        }
    
        public int Ma { get; set; }
        public Nullable<int> SoLuongHocSinh { get; set; }
        public Nullable<int> HocPhiMotBuoi { get; set; }
        public Nullable<bool> DaKetThuc { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaGiaoVien { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public Nullable<int> MaMucHocPhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienLaiThuHocPhi> BienLaiThuHocPhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiHoc> BuoiHocs { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual MucHocPhi MucHocPhi { get; set; }
    }
}
